### ISSUE TITLE
Impossible to use fixture with nested fixture when it is in other file

### ISSUE THREAD

**Issue by hh-h** [Ovsyanka83/pytest-fixture-classes#1]
example:

file with fixtures, let's say fix.py
```python
from pytest_fixture_classes import fixture_class


@fixture_class(name="first_fixture")
class FirstFixture:
    def __call__(self) -> None:
        ...


@fixture_class(name="second_fixture")
class SecondFixture:
    first_fixture: FirstFixture

    def __call__(self) -> None:
        self.first_fixture()
```

file with tests, let's say tests.py
```python
from .fix import SecondFixture


def test_kek(second_fixture: SecondFixture) -> None:
    second_fixture()

```

if you run pytest you'll get this error
```
E       fixture 'first_fixture' not found
>       available fixtures: ..., second_fixture, ...
>       use 'pytest --fixtures [testpath]' for help on them.

```

**Comment by zmievsa** [comment]
Am on it.

**Comment by zmievsa** [comment]
It's not a bug in pytest-fixture-classes. It's an expected behavior in pytest. To verify so, I created the following scenario similar to yours:

```python
# test_foo.py
import pytest


@pytest.fixture
def first_fixture() -> None:
    ...


@pytest.fixture
def second_fixture(first_fixture):
    def inner(self) -> None:
        first_fixture()

    return inner

```

```python
# test_bar.py

from .test_foo import second_fixture


def test_kek(second_fixture) -> None:
    second_fixture()
```

Same error: `fixture 'first_fixture' not found`. When you import fixtures like that, you need to import either the entire file (wildcard) or to import all used fixtures. That happens because you're not supposed to define fixtures outside of conftest.py. However, you can create multiple conftest.py files in subdirectories.

But thank you for this issue: it helped me find a few minor display bugs in pytest-fixture-classes.
